set(_CATKIN_CURRENT_PACKAGE "apriltag2_ros")
set(apriltag2_ros_VERSION "0.0.0")
set(apriltag2_ros_MAINTAINER "fschiano <fschiano@todo.todo>")
set(apriltag2_ros_PACKAGE_FORMAT "1")
set(apriltag2_ros_BUILD_DEPENDS "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_generation" "nodelet" "std_msgs" "cmake_modules")
set(apriltag2_ros_BUILD_EXPORT_DEPENDS "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_runtime" "nodelet" "std_msgs")
set(apriltag2_ros_BUILDTOOL_DEPENDS "catkin")
set(apriltag2_ros_BUILDTOOL_EXPORT_DEPENDS )
set(apriltag2_ros_EXEC_DEPENDS "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_runtime" "nodelet" "std_msgs")
set(apriltag2_ros_RUN_DEPENDS "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_runtime" "nodelet" "std_msgs")
set(apriltag2_ros_TEST_DEPENDS )
set(apriltag2_ros_DOC_DEPENDS )
set(apriltag2_ros_DEPRECATED "")